[workspace]
resolver = "3"

members = [
    "example",
    "snafu-tracing",
    "snafu-tracing-macro"
]

[workspace.dependencies]
snafu = "0.8"
snafu-tracing-macro = { version = "0.8.0", path = "snafu-tracing-macro" }
snafu-tracing = { version = "0.8.3", path = "snafu-tracing" }
